configured_endpoints: 12
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/greenflash%2Fgreenflash-public-api-f1cd8a0e3beee8e2172dc4e673c92da9be394c64be40d8c4ddaa8132b2c9bb3f.yml
openapi_spec_hash: 655e3b92ec03084c93e87f3cb3d91e91
config_hash: 8e92ad69f2456950f5163eca2f6ab6cb
